name: Update latest earning reports cron
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update Earning Reports
        run: |
          curl --request GET \
          --url 'https://trossearnings.vercel.app/api/filings' \
